import type { Metadata } from "next";
import "./globals.css";
import type { Viewport } from 'next';
import { Header } from "./header";

export const viewport: Viewport = {
	width: "500",
}
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body>
				<div id="background" />
				<div id="vp">
					<Header />
					<main>{children}</main>
					<footer>
						developed by{" "}
						<a href="https://bsky.app/profile/tomo-x.bsky.social" target="_blank" rel="noopener noreferrer">
							@tomo-x
						</a>
						<br />
						このプロジェクトはオープンソースです。
						<a href="https://github.com/tomo-x7/diagnosky" target="_blank" rel="noopener noreferrer">
							リポジトリ
						</a>
					</footer>
				</div>
			</body>
		</html>
	);
}
